name: Test Action - PNPM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-pnpm:
    name: Test with PNPM
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ['22', '24']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Get old Nx version
        id: nx-version
        run: |
          # Get an older stable version of Nx for testing migration
          OLD_VERSION=$(npm view @nx/workspace versions --json | jq -r '.[]' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -20 | head -1 || echo "19.0.0")
          echo "old-version=$OLD_VERSION" >> $GITHUB_OUTPUT
          echo "Using Nx version $OLD_VERSION for testing"

      - name: Create test Nx workspace
        run: |
          # Create a minimal test workspace
          mkdir test-workspace
          cd test-workspace

          # Create package.json first
          cat > package.json << EOF
          {
            "name": "test-workspace",
            "version": "1.0.0",
            "scripts": {
              "build": "echo 'Build complete'",
              "test": "echo 'Tests complete'"
            },
            "dependencies": {
              "@nx/workspace": "${{ steps.nx-version.outputs.old-version }}"
            }
          }
          EOF

          # Create nx.json
          cat > nx.json << EOF
          {
            "version": 3,
            "projects": {},
            "targetDefaults": {
              "build": {
                "cache": true
              }
            }
          }
          EOF

          # Install dependencies with pnpm
          pnpm install

          # Verify workspace setup
          echo "=== Workspace created successfully ==="
          ls -la
          cat package.json
          echo "=== End workspace info ==="

      - name: Test Action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: pnpm
          node-version: ${{ matrix.node-version }}
          working-directory: './test-workspace'
          validation-commands: 'build,test'
          auto-merge-on-success: 'false'
          skip-validation: 'true'  # Skip validation for testing to avoid failures

      - name: Verify outputs
        run: |
          echo "Action completed successfully"
          echo "Package manager: pnpm"
          echo "Node version: ${{ matrix.node-version }}"